# Generated by Django 4.1.3 on 2022-12-08 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grades', '0002_alter_grade_submission'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='grade',
            options={'permissions': (('add_comment', 'Can add comment'), ('change_grade_value', 'Can change grade'))},
        ),
        migrations.AlterField(
            model_name='grade',
            name='comment',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
